window.cards = [
  // ===== Developer Fundamentals =====
  {
    id: "Q1",
    question: "A developer needs to replace a legacy JavaScript button that prepopulates fields on a new record. Which Lightning-friendly feature should be used?",
    options: [
      { letter: "A", text: "Validation Rules" },
      { letter: "B", text: "Quick Actions" },
      { letter: "C", text: "Outbound Messaging" },
      { letter: "D", text: "Apex Triggers" },
    ],
    answer: "B",
    explanation: "Quick Actions (with predefined field values) are the standard, Lightning-supported replacement for JavaScript buttons that prepopulate data.",
  },
  {
    id: "Q2",
    question: "A developer wants to create a unique identifier for Order records imported from an external system. Which field configuration should be used?",
    options: [
      { letter: "A", text: "Indirect Lookup field" },
      { letter: "B", text: "Text field marked as Unique and External ID" },
      { letter: "C", text: "Auto-number field" },
      { letter: "D", text: "Master-Detail relationship" },
    ],
    answer: "B",
    explanation: "An External ID lets you match records to an external system, and the Unique attribute prevents duplicate values.",
  },
  {
    id: "Q3",
    question: "What is a characteristic of a Master-Detail relationship compared to a Lookup relationship?",
    options: [
      { letter: "A", text: "The child record can exist without a parent." },
      { letter: "B", text: "The security/access of the child is determined by the parent." },
      { letter: "C", text: "You can have up to 40 Master-Detail fields per object." },
      { letter: "D", text: "Deleting the parent does not delete the child." },
    ],
    answer: "B",
    explanation: "In Master-Detail, the detail (child) record inherits sharing and ownership from the master, and deleting the master cascade-deletes children.",
  },
  {
    id: "Q4",
    question: "How many Master-Detail relationship fields can a custom object have?",
    options: [
      { letter: "A", text: "1" },
      { letter: "B", text: "2" },
      { letter: "C", text: "25" },
      { letter: "D", text: "40" },
    ],
    answer: "B",
    explanation: "A custom object can have up to 2 Master-Detail relationships (making it a junction object) and up to 40 total relationship fields.",
  },
  {
    id: "Q5",
    question: "A developer needs to relate two objects in a many-to-many relationship. What should be created?",
    options: [
      { letter: "A", text: "A roll-up summary field" },
      { letter: "B", text: "A junction object with two Master-Detail relationships" },
      { letter: "C", text: "A hierarchical relationship" },
      { letter: "D", text: "An external lookup" },
    ],
    answer: "B",
    explanation: "Many-to-many relationships are modeled with a junction object that has two Master-Detail relationships to the related objects.",
  },
  {
    id: "Q6",
    question: "On which type of relationship can a roll-up summary field be created on the parent object?",
    options: [
      { letter: "A", text: "Lookup relationship" },
      { letter: "B", text: "Master-Detail relationship" },
      { letter: "C", text: "External lookup relationship" },
      { letter: "D", text: "Any relationship type" },
    ],
    answer: "B",
    explanation: "Standard roll-up summary fields can only be created on the master side of a Master-Detail relationship.",
  },
  {
    id: "Q7",
    question: "Which data type should be used to store a value such as 'true' or 'false' on a record?",
    options: [
      { letter: "A", text: "Picklist" },
      { letter: "B", text: "Checkbox" },
      { letter: "C", text: "Text" },
      { letter: "D", text: "Number" },
    ],
    answer: "B",
    explanation: "A Checkbox field stores a Boolean value (true/false) in Salesforce.",
  },
  {
    id: "Q8",
    question: "A developer wants the org to follow a specific governance model where metadata changes are tracked. Which org should development be done in?",
    options: [
      { letter: "A", text: "Production org" },
      { letter: "B", text: "A sandbox or scratch org" },
      { letter: "C", text: "A trial org" },
      { letter: "D", text: "A Developer Edition org owned by the customer" },
    ],
    answer: "B",
    explanation: "Development and testing should be done in sandboxes or scratch orgs, never directly in production.",
  },
  {
    id: "Q9",
    question: "What is the maximum number of characters allowed in a standard Text field?",
    options: [
      { letter: "A", text: "80" },
      { letter: "B", text: "255" },
      { letter: "C", text: "1000" },
      { letter: "D", text: "32768" },
    ],
    answer: "B",
    explanation: "A standard Text field holds up to 255 characters. Use Text Area (Long) for larger values.",
  },
  {
    id: "Q10",
    question: "Which feature lets an administrator capture different field values, page layouts, and business processes for the same object based on a Record Type?",
    options: [
      { letter: "A", text: "Permission Sets" },
      { letter: "B", text: "Record Types" },
      { letter: "C", text: "Field-Level Security" },
      { letter: "D", text: "Sharing Rules" },
    ],
    answer: "B",
    explanation: "Record Types allow different picklist values, page layouts, and business processes for the same object based on user profile.",
  },

  // ===== Apex Basics & Logic =====
  {
    id: "Q11",
    question: "A developer needs to perform a DML operation but wants successful records to be saved even if others fail. Which statement should be used?",
    options: [
      { letter: "A", text: "insert records;" },
      { letter: "B", text: "Database.insert(records, false);" },
      { letter: "C", text: "Database.insert(records, true);" },
      { letter: "D", text: "upsert records;" },
    ],
    answer: "B",
    explanation: "The second parameter (allOrNone) set to false allows partial success; failed records are reported in the returned SaveResult.",
  },
  {
    id: "Q12",
    question: "What is the correct method signature for an Invocable Method that accepts a list of IDs and returns a list of strings?",
    options: [
      { letter: "A", text: "@InvocableMethod public static List<String> myMethod(List<Id> ids) {}" },
      { letter: "B", text: "@InvocableMethod public List<String> myMethod(Id ids) {}" },
      { letter: "C", text: "@InvocableMethod global String myMethod(List<Id> ids) {}" },
      { letter: "D", text: "@InvocableMethod public static Map<Id, String> myMethod(List<Id> ids) {}" },
    ],
    answer: "A",
    explanation: "Invocable methods must be static, public/global, and take a List as input (one parameter) for bulkification.",
  },
  {
    id: "Q13",
    question: "Which collection type stores unique, unordered values?",
    options: [
      { letter: "A", text: "List" },
      { letter: "B", text: "Set" },
      { letter: "C", text: "Map" },
      { letter: "D", text: "Array" },
    ],
    answer: "B",
    explanation: "A Set is an unordered collection that does not allow duplicate values.",
  },
  {
    id: "Q14",
    question: "How many records can a single SOQL query return before hitting the synchronous governor limit?",
    options: [
      { letter: "A", text: "10,000" },
      { letter: "B", text: "50,000" },
      { letter: "C", text: "100" },
      { letter: "D", text: "100,000" },
    ],
    answer: "B",
    explanation: "Total records retrieved by SOQL queries in a single transaction is limited to 50,000.",
  },
  {
    id: "Q15",
    question: "What is the SOQL query limit per synchronous Apex transaction?",
    options: [
      { letter: "A", text: "50" },
      { letter: "B", text: "100" },
      { letter: "C", text: "150" },
      { letter: "D", text: "200" },
    ],
    answer: "B",
    explanation: "A synchronous transaction allows up to 100 SOQL queries (200 for asynchronous).",
  },
  {
    id: "Q16",
    question: "What is the total number of DML statements allowed per Apex transaction?",
    options: [
      { letter: "A", text: "100" },
      { letter: "B", text: "150" },
      { letter: "C", text: "200" },
      { letter: "D", text: "50" },
    ],
    answer: "B",
    explanation: "Apex allows a maximum of 150 DML statements per transaction.",
  },
  {
    id: "Q17",
    question: "A developer wants to query records including those in the Recycle Bin and archived activities. Which keyword should be used?",
    options: [
      { letter: "A", text: "SELECT ... ALL ROWS" },
      { letter: "B", text: "SELECT ... INCLUDE DELETED" },
      { letter: "C", text: "SELECT ... WITH RECYCLE" },
      { letter: "D", text: "SELECT ... ARCHIVED" },
    ],
    answer: "A",
    explanation: "The ALL ROWS keyword returns deleted and archived records in a SOQL query.",
  },
  {
    id: "Q18",
    question: "Which statement correctly retrieves child records using a relationship query from Account?",
    options: [
      { letter: "A", text: "SELECT Name, (SELECT LastName FROM Contacts) FROM Account" },
      { letter: "B", text: "SELECT Name, Contacts.LastName FROM Account" },
      { letter: "C", text: "SELECT Name FROM Account JOIN Contact" },
      { letter: "D", text: "SELECT Name, Contact.LastName FROM Account" },
    ],
    answer: "A",
    explanation: "A parent-to-child (subquery) relationship query uses the child relationship name (Contacts) inside parentheses.",
  },
  {
    id: "Q19",
    question: "In a child-to-parent SOQL query from Contact, how do you reference the parent Account's name?",
    options: [
      { letter: "A", text: "SELECT Account.Name FROM Contact" },
      { letter: "B", text: "SELECT Accounts.Name FROM Contact" },
      { letter: "C", text: "SELECT (SELECT Name FROM Account) FROM Contact" },
      { letter: "D", text: "SELECT Parent.Name FROM Contact" },
    ],
    answer: "A",
    explanation: "Child-to-parent queries use dot notation with the relationship name (Account.Name).",
  },
  {
    id: "Q20",
    question: "Which annotation makes an Apex method available to be called from a Lightning Web Component?",
    options: [
      { letter: "A", text: "@AuraEnabled" },
      { letter: "B", text: "@RemoteAction" },
      { letter: "C", text: "@InvocableMethod" },
      { letter: "D", text: "@future" },
    ],
    answer: "A",
    explanation: "@AuraEnabled exposes Apex methods (and properties) to Lightning Web Components and Aura components.",
  },
  {
    id: "Q21",
    question: "Which annotation is required to make an Apex method cacheable when called imperatively or via wire from an LWC?",
    options: [
      { letter: "A", text: "@AuraEnabled(cacheable=true)" },
      { letter: "B", text: "@ReadOnly" },
      { letter: "C", text: "@future(callout=true)" },
      { letter: "D", text: "@RemoteAction(cacheable=true)" },
    ],
    answer: "A",
    explanation: "@AuraEnabled(cacheable=true) enables client-side caching and is required for use with the @wire service.",
  },
  {
    id: "Q22",
    question: "What does the 'with sharing' keyword on an Apex class enforce?",
    options: [
      { letter: "A", text: "Field-level security" },
      { letter: "B", text: "Object-level permissions (CRUD)" },
      { letter: "C", text: "The sharing rules of the current user" },
      { letter: "D", text: "Validation rules" },
    ],
    answer: "C",
    explanation: "'with sharing' enforces the record-level sharing rules of the running user. It does NOT enforce FLS or CRUD automatically.",
  },
  {
    id: "Q23",
    question: "By default (no sharing keyword), how does an Apex class execute regarding record access?",
    options: [
      { letter: "A", text: "Always with sharing" },
      { letter: "B", text: "Always without sharing" },
      { letter: "C", text: "It runs in system context (without sharing enforced) unless inherited" },
      { letter: "D", text: "It throws a compile error" },
    ],
    answer: "C",
    explanation: "Without an explicit keyword, Apex runs in system mode; sharing is only enforced if inherited from a calling class that declared it.",
  },
  {
    id: "Q24",
    question: "Which keyword is used to define a class whose sharing behavior is inherited from the calling class?",
    options: [
      { letter: "A", text: "without sharing" },
      { letter: "B", text: "inherited sharing" },
      { letter: "C", text: "with sharing" },
      { letter: "D", text: "global sharing" },
    ],
    answer: "B",
    explanation: "'inherited sharing' makes the class run with the sharing mode of the class that called it.",
  },
  {
    id: "Q25",
    question: "What is the result of a SOQL query that returns no rows when assigned to a single sObject variable?",
    options: [
      { letter: "A", text: "It returns null" },
      { letter: "B", text: "It throws a QueryException (List has no rows for assignment)" },
      { letter: "C", text: "It returns an empty sObject" },
      { letter: "D", text: "It returns false" },
    ],
    answer: "B",
    explanation: "Assigning a zero-row query to a single sObject throws 'List has no rows for assignment to SObject'. Use a List to avoid it.",
  },

  // ===== Triggers =====
  {
    id: "Q26",
    question: "A developer is writing logic on the Contact object. Which two practices ensure scalable, maintainable code? (Choose 2)",
    options: [
      { letter: "A", text: "Place all business logic directly in the trigger body." },
      { letter: "B", text: "Use a single trigger per object." },
      { letter: "C", text: "Move logic into an Apex handler class." },
      { letter: "D", text: "Use Trigger.new only in before contexts." },
    ],
    answer: "B, C",
    explanation: "One trigger per object plus delegating logic to a handler class are core Salesforce best practices.",
  },
  {
    id: "Q27",
    question: "In which trigger context is Trigger.new read-only?",
    options: [
      { letter: "A", text: "before insert" },
      { letter: "B", text: "before update" },
      { letter: "C", text: "after update" },
      { letter: "D", text: "before delete" },
    ],
    answer: "C",
    explanation: "In after-triggers, Trigger.new records are read-only. To modify field values without DML, use before-triggers.",
  },
  {
    id: "Q28",
    question: "Which trigger context variable is available in a 'before insert' trigger?",
    options: [
      { letter: "A", text: "Trigger.old" },
      { letter: "B", text: "Trigger.oldMap" },
      { letter: "C", text: "Trigger.new" },
      { letter: "D", text: "Trigger.newMap" },
    ],
    answer: "C",
    explanation: "Trigger.new is available on insert and update. Trigger.old/oldMap are not available on insert, and Trigger.newMap is not available in before insert (IDs not yet assigned).",
  },
  {
    id: "Q29",
    question: "To set a field value on the record being inserted with the least overhead, in which context should the assignment occur?",
    options: [
      { letter: "A", text: "after insert, then perform an update DML" },
      { letter: "B", text: "before insert, modifying Trigger.new directly" },
      { letter: "C", text: "after update" },
      { letter: "D", text: "It cannot be done in a trigger" },
    ],
    answer: "B",
    explanation: "In before insert/update you can modify Trigger.new directly without an additional DML statement.",
  },
  {
    id: "Q30",
    question: "A trigger needs the record's ID to create related records. Which context should be used?",
    options: [
      { letter: "A", text: "before insert" },
      { letter: "B", text: "after insert" },
      { letter: "C", text: "before delete" },
      { letter: "D", text: "before update" },
    ],
    answer: "B",
    explanation: "Record IDs are assigned only after insert, so an after-insert trigger is required to reference them.",
  },
  {
    id: "Q31",
    question: "What happens to the entire transaction when an unhandled exception occurs in a trigger?",
    options: [
      { letter: "A", text: "Only the failing record is rolled back" },
      { letter: "B", text: "The entire transaction is rolled back" },
      { letter: "C", text: "Nothing is rolled back" },
      { letter: "D", text: "Only DML after the error is rolled back" },
    ],
    answer: "B",
    explanation: "An unhandled exception rolls back the entire transaction, including all DML performed within it.",
  },
  {
    id: "Q32",
    question: "Which method is best used to prevent recursive trigger execution?",
    options: [
      { letter: "A", text: "Using a static Boolean variable as a flag" },
      { letter: "B", text: "Adding a delay with sleep()" },
      { letter: "C", text: "Wrapping logic in a try/catch" },
      { letter: "D", text: "Using @future on every method" },
    ],
    answer: "A",
    explanation: "A static Boolean flag persists across trigger invocations within a transaction and can guard against recursion.",
  },
  {
    id: "Q33",
    question: "A developer wants to add a validation error to a specific record in a trigger. Which method should be used?",
    options: [
      { letter: "A", text: "record.addError('message')" },
      { letter: "B", text: "throw new Exception('message')" },
      { letter: "C", text: "System.assert(false)" },
      { letter: "D", text: "Trigger.abort()" },
    ],
    answer: "A",
    explanation: "addError() on an sObject or field blocks the DML for that record and displays the message to the user.",
  },

  // ===== Asynchronous Apex =====
  {
    id: "Q34",
    question: "Which asynchronous Apex feature should be used to process a very large number of records (millions) in batches?",
    options: [
      { letter: "A", text: "@future method" },
      { letter: "B", text: "Batch Apex (Database.Batchable)" },
      { letter: "C", text: "Queueable Apex" },
      { letter: "D", text: "Scheduled Flow" },
    ],
    answer: "B",
    explanation: "Batch Apex processes records in chunks and is designed for large data volumes, with a higher cumulative governor limit per execute.",
  },
  {
    id: "Q35",
    question: "Which interface must a class implement to be run as a batch job?",
    options: [
      { letter: "A", text: "Database.Batchable" },
      { letter: "B", text: "Schedulable" },
      { letter: "C", text: "Queueable" },
      { letter: "D", text: "Database.Stateful" },
    ],
    answer: "A",
    explanation: "Batch Apex requires implementing Database.Batchable with start, execute, and finish methods.",
  },
  {
    id: "Q36",
    question: "Which interface allows a batch job to retain instance variable state across execute() calls?",
    options: [
      { letter: "A", text: "Database.AllowsCallouts" },
      { letter: "B", text: "Database.Stateful" },
      { letter: "C", text: "Schedulable" },
      { letter: "D", text: "Queueable" },
    ],
    answer: "B",
    explanation: "Implementing Database.Stateful preserves instance member variables between batch execute() invocations.",
  },
  {
    id: "Q37",
    question: "Which two are characteristics of a @future method? (Choose 2)",
    options: [
      { letter: "A", text: "It must return void." },
      { letter: "B", text: "It can return a List of records." },
      { letter: "C", text: "It can only take primitive types or collections of primitives as parameters." },
      { letter: "D", text: "It can take sObjects as parameters." },
    ],
    answer: "A, C",
    explanation: "@future methods must be static, return void, and accept only primitives or collections of primitives (not sObjects).",
  },
  {
    id: "Q38",
    question: "Which asynchronous feature provides a job ID and supports chaining one job from another?",
    options: [
      { letter: "A", text: "@future" },
      { letter: "B", text: "Queueable Apex" },
      { letter: "C", text: "Outbound message" },
      { letter: "D", text: "Workflow rule" },
    ],
    answer: "B",
    explanation: "Queueable Apex returns a job ID (via System.enqueueJob) and supports chaining by enqueuing another Queueable from execute().",
  },
  {
    id: "Q39",
    question: "How is a callout to an external web service allowed from a method that is invoked by a trigger?",
    options: [
      { letter: "A", text: "Perform the callout synchronously in the trigger" },
      { letter: "B", text: "Call a @future(callout=true) method" },
      { letter: "C", text: "Use System.debug before the callout" },
      { letter: "D", text: "Callouts are never allowed from triggers" },
    ],
    answer: "B",
    explanation: "Triggers can't make synchronous callouts; the callout must be made asynchronously, e.g. via a @future(callout=true) method or Queueable.",
  },
  {
    id: "Q40",
    question: "Which interface is used to run Apex on a schedule?",
    options: [
      { letter: "A", text: "Schedulable" },
      { letter: "B", text: "Batchable" },
      { letter: "C", text: "Queueable" },
      { letter: "D", text: "Callable" },
    ],
    answer: "A",
    explanation: "The Schedulable interface (with the execute(SchedulableContext) method) lets Apex run on a defined schedule via System.schedule.",
  },

  // ===== Process Automation (Declarative) =====
  {
    id: "Q41",
    question: "Salesforce recommends migrating Workflow Rules and Process Builder to which tool?",
    options: [
      { letter: "A", text: "Apex Triggers" },
      { letter: "B", text: "Flow" },
      { letter: "C", text: "Validation Rules" },
      { letter: "D", text: "Outbound Messaging" },
    ],
    answer: "B",
    explanation: "Salesforce is retiring Workflow Rules and Process Builder; Flow is the recommended go-forward automation tool.",
  },
  {
    id: "Q42",
    question: "Which Flow type runs in the background without user interaction, triggered by a record change?",
    options: [
      { letter: "A", text: "Screen Flow" },
      { letter: "B", text: "Record-Triggered Flow" },
      { letter: "C", text: "Schedule-Triggered Flow only" },
      { letter: "D", text: "Autolaunched Flow with no trigger" },
    ],
    answer: "B",
    explanation: "A Record-Triggered Flow runs automatically when a record is created, updated, or deleted, without user interaction.",
  },
  {
    id: "Q43",
    question: "To update fields on the same record that triggered a flow with the best performance, which flow configuration should be used?",
    options: [
      { letter: "A", text: "After-save flow with an Update Records element" },
      { letter: "B", text: "Before-save (fast field update) record-triggered flow" },
      { letter: "C", text: "Screen flow" },
      { letter: "D", text: "Scheduled flow" },
    ],
    answer: "B",
    explanation: "Before-save record-triggered flows update the triggering record in memory without an extra DML, making them the most efficient for same-record updates.",
  },
  {
    id: "Q44",
    question: "Which two features support sending an outbound message declaratively (without Apex)? (Choose 2)",
    options: [
      { letter: "A", text: "Flow" },
      { letter: "B", text: "Approval Process" },
      { letter: "C", text: "Lightning Web Components" },
      { letter: "D", text: "Validation Rules" },
    ],
    answer: "A, B",
    explanation: "Flows and Approval Processes can trigger outbound messages declaratively (workflow actions also can, but it is being retired).",
  },
  {
    id: "Q45",
    question: "What is the purpose of a Validation Rule?",
    options: [
      { letter: "A", text: "To automatically populate field values" },
      { letter: "B", text: "To prevent records from being saved when criteria evaluate to true" },
      { letter: "C", text: "To send email alerts" },
      { letter: "D", text: "To schedule batch jobs" },
    ],
    answer: "B",
    explanation: "A validation rule blocks the save and shows an error when its formula evaluates to true.",
  },
  {
    id: "Q46",
    question: "An approval process needs to lock a record so users cannot edit it while pending approval. How is this achieved?",
    options: [
      { letter: "A", text: "Use a validation rule" },
      { letter: "B", text: "Enable record locking in the approval process initial submission actions" },
      { letter: "C", text: "Write an Apex trigger" },
      { letter: "D", text: "Records cannot be locked" },
    ],
    answer: "B",
    explanation: "Approval processes can automatically lock records on submission, which is configured in the process settings/actions.",
  },

  // ===== User Interface: Lightning Web Components & Visualforce =====
  {
    id: "Q47",
    question: "Which decorator is used in a Lightning Web Component to read Salesforce data reactively via an Apex method or wire adapter?",
    options: [
      { letter: "A", text: "@api" },
      { letter: "B", text: "@track" },
      { letter: "C", text: "@wire" },
      { letter: "D", text: "@salesforce" },
    ],
    answer: "C",
    explanation: "@wire reactively provisions data from an Apex method (cacheable) or a Lightning Data Service wire adapter.",
  },
  {
    id: "Q48",
    question: "Which decorator exposes a public property or method on an LWC so a parent component can set or call it?",
    options: [
      { letter: "A", text: "@api" },
      { letter: "B", text: "@track" },
      { letter: "C", text: "@wire" },
      { letter: "D", text: "@AuraEnabled" },
    ],
    answer: "A",
    explanation: "@api marks a field or method as public, allowing parent components to pass data in or invoke the method.",
  },
  {
    id: "Q49",
    question: "How does a child LWC communicate an event up to its parent?",
    options: [
      { letter: "A", text: "By calling the parent's method directly" },
      { letter: "B", text: "By dispatching a CustomEvent" },
      { letter: "C", text: "By using @track" },
      { letter: "D", text: "By importing the parent class" },
    ],
    answer: "B",
    explanation: "Child-to-parent communication uses this.dispatchEvent(new CustomEvent(...)); the parent listens with an on<eventname> handler.",
  },
  {
    id: "Q50",
    question: "Which base Lightning component provides record create/edit/view with built-in field-level security and no Apex required?",
    options: [
      { letter: "A", text: "lightning-record-form / lightning-record-edit-form" },
      { letter: "B", text: "apex:page" },
      { letter: "C", text: "lightning-datatable" },
      { letter: "D", text: "aura:iteration" },
    ],
    answer: "A",
    explanation: "lightning-record-form and lightning-record-edit-form use Lightning Data Service to handle records while respecting FLS, without Apex.",
  },
  {
    id: "Q51",
    question: "What does Lightning Data Service (LDS) provide to components?",
    options: [
      { letter: "A", text: "A way to write SOQL directly in markup" },
      { letter: "B", text: "Access to create, read, update, delete records without Apex, with shared caching" },
      { letter: "C", text: "Server-side batch processing" },
      { letter: "D", text: "A replacement for governor limits" },
    ],
    answer: "B",
    explanation: "LDS lets components work with records (CRUD) without Apex, automatically enforcing FLS and sharing a client cache across components.",
  },
  {
    id: "Q52",
    question: "In a Visualforce page, which attribute on <apex:page> binds the page to an Apex controller class?",
    options: [
      { letter: "A", text: "extensions" },
      { letter: "B", text: "controller" },
      { letter: "C", text: "standardController" },
      { letter: "D", text: "action" },
    ],
    answer: "B",
    explanation: "The controller attribute binds a custom Apex controller. standardController binds a standard object controller, and extensions adds controller extensions.",
  },
  {
    id: "Q53",
    question: "Which Visualforce feature provides built-in CRUD logic for a standard or custom object?",
    options: [
      { letter: "A", text: "Custom controller" },
      { letter: "B", text: "Standard controller" },
      { letter: "C", text: "Controller extension" },
      { letter: "D", text: "Remote action" },
    ],
    answer: "B",
    explanation: "A standard controller provides out-of-the-box save, edit, delete, and view actions for the associated object.",
  },
  {
    id: "Q54",
    question: "A developer wants to display a list of records in an LWC that supports inline editing and sorting out of the box. Which component is best?",
    options: [
      { letter: "A", text: "lightning-datatable" },
      { letter: "B", text: "lightning-card" },
      { letter: "C", text: "lightning-input" },
      { letter: "D", text: "template for:each" },
    ],
    answer: "A",
    explanation: "lightning-datatable provides tabular display with built-in sorting, inline editing, and row selection.",
  },
  {
    id: "Q55",
    question: "Which file in an LWC bundle defines where the component can be used (e.g., App Page, Record Page)?",
    options: [
      { letter: "A", text: "The .js file" },
      { letter: "B", text: "The .html file" },
      { letter: "C", text: "The .js-meta.xml configuration file" },
      { letter: "D", text: "The .css file" },
    ],
    answer: "C",
    explanation: "The *.js-meta.xml file declares API version, exposure, and the targets where the component can be placed.",
  },
  {
    id: "Q56",
    question: "How can an LWC navigate the user to a record page in Lightning Experience?",
    options: [
      { letter: "A", text: "window.location with a hardcoded URL" },
      { letter: "B", text: "The NavigationMixin and a 'standard__recordPage' page reference" },
      { letter: "C", text: "An Apex PageReference" },
      { letter: "D", text: "A Visualforce redirect" },
    ],
    answer: "B",
    explanation: "LWCs use NavigationMixin.Navigate with a page reference (e.g., standard__recordPage) for navigation in Lightning Experience.",
  },
  {
    id: "Q57",
    question: "Which technology should be used to build a custom UI component that works in both Lightning Experience and the Salesforce mobile app and is the current Salesforce standard?",
    options: [
      { letter: "A", text: "Visualforce" },
      { letter: "B", text: "Lightning Web Components" },
      { letter: "C", text: "S-Controls" },
      { letter: "D", text: "JavaScript buttons" },
    ],
    answer: "B",
    explanation: "Lightning Web Components are the modern, recommended framework for custom UI across Lightning Experience and mobile.",
  },

  // ===== Testing =====
  {
    id: "Q58",
    question: "What minimum overall code coverage is required to deploy Apex to a production org?",
    options: [
      { letter: "A", text: "50%" },
      { letter: "B", text: "75%" },
      { letter: "C", text: "90%" },
      { letter: "D", text: "100%" },
    ],
    answer: "B",
    explanation: "At least 75% overall code coverage is required, and every trigger must have some coverage, to deploy to production.",
  },
  {
    id: "Q59",
    question: "Which annotation marks an Apex class as a test class?",
    options: [
      { letter: "A", text: "@isTest" },
      { letter: "B", text: "@testMethod" },
      { letter: "C", text: "@testSetup" },
      { letter: "D", text: "@runAs" },
    ],
    answer: "A",
    explanation: "@isTest marks a class (or method) as test code, which doesn't count against org Apex limits.",
  },
  {
    id: "Q60",
    question: "By default, can a test method see existing data already stored in the org (not created by the test)?",
    options: [
      { letter: "A", text: "Yes, all data is visible" },
      { letter: "B", text: "No, tests run in data isolation and cannot see most existing records by default" },
      { letter: "C", text: "Only Account records are visible" },
      { letter: "D", text: "Only if @runAs is used" },
    ],
    answer: "B",
    explanation: "Tests are data-isolated by default (since API 24); they should create their own test data. Some setup/metadata objects are exceptions.",
  },
  {
    id: "Q61",
    question: "Which methods mark the start and end of a block to reset governor limits and force asynchronous execution to complete in a test?",
    options: [
      { letter: "A", text: "Test.startTest() and Test.stopTest()" },
      { letter: "B", text: "Test.begin() and Test.end()" },
      { letter: "C", text: "System.start() and System.stop()" },
      { letter: "D", text: "Test.setup() and Test.teardown()" },
    ],
    answer: "A",
    explanation: "Test.startTest()/stopTest() give a fresh set of governor limits and force queued async work to run synchronously by stopTest().",
  },
  {
    id: "Q62",
    question: "Which annotation creates test records once and makes them available to all test methods in the class?",
    options: [
      { letter: "A", text: "@isTest" },
      { letter: "B", text: "@testSetup" },
      { letter: "C", text: "@future" },
      { letter: "D", text: "@testVisible" },
    ],
    answer: "B",
    explanation: "A @testSetup method runs once before each test method, creating common data efficiently and rolling back changes between methods.",
  },
  {
    id: "Q63",
    question: "How can a test verify code behaves correctly for a specific user's permissions?",
    options: [
      { letter: "A", text: "System.runAs(user)" },
      { letter: "B", text: "Test.loadData(user)" },
      { letter: "C", text: "System.assert(user)" },
      { letter: "D", text: "Test.setUser(user)" },
    ],
    answer: "A",
    explanation: "System.runAs(user) executes a block of test code in the context of a specified user, useful for testing sharing and permissions.",
  },
  {
    id: "Q64",
    question: "Which is a best practice for writing meaningful Apex tests?",
    options: [
      { letter: "A", text: "Only test the positive path to maximize coverage quickly" },
      { letter: "B", text: "Use System.assert statements to verify expected outcomes" },
      { letter: "C", text: "Use SeeAllData=true on every test" },
      { letter: "D", text: "Avoid bulk testing" },
    ],
    answer: "B",
    explanation: "Tests should assert expected results (not just run code), test positive/negative/bulk scenarios, and avoid relying on org data.",
  },
  {
    id: "Q65",
    question: "How should a test for a trigger verify bulk behavior?",
    options: [
      { letter: "A", text: "Insert a single record" },
      { letter: "B", text: "Insert at least 200 records to validate bulkification" },
      { letter: "C", text: "Insert 10 records" },
      { letter: "D", text: "Use SeeAllData=true" },
    ],
    answer: "B",
    explanation: "Testing with 200+ records validates that the code handles the standard batch size and avoids per-record limit issues.",
  },
  {
    id: "Q66",
    question: "Which class is used to set a mock HTTP response when testing a callout?",
    options: [
      { letter: "A", text: "HttpCalloutMock implementation set via Test.setMock" },
      { letter: "B", text: "Test.startTest only" },
      { letter: "C", text: "System.runAs" },
      { letter: "D", text: "Database.Stateful" },
    ],
    answer: "A",
    explanation: "Implement HttpCalloutMock (or use StaticResourceCalloutMock) and register it with Test.setMock to simulate callout responses.",
  },

  // ===== Debugging & Deployment =====
  {
    id: "Q67",
    question: "Which Developer Console Log Inspector tab shows the execution time of various processes in a transaction?",
    options: [
      { letter: "A", text: "Stack Tree" },
      { letter: "B", text: "Execution Log" },
      { letter: "C", text: "Timeline" },
      { letter: "D", text: "Source" },
    ],
    answer: "C",
    explanation: "The Timeline tab visualizes how time was spent across Apex, DB, callouts, workflow, and other categories.",
  },
  {
    id: "Q68",
    question: "Which tool allows running ad-hoc Apex code anonymously for testing or debugging?",
    options: [
      { letter: "A", text: "Execute Anonymous Window" },
      { letter: "B", text: "Schema Builder" },
      { letter: "C", text: "Process Builder" },
      { letter: "D", text: "Data Loader" },
    ],
    answer: "A",
    explanation: "The Execute Anonymous window (in Developer Console) runs a block of Apex on demand without deploying it.",
  },
  {
    id: "Q69",
    question: "What is the recommended method to write debug output to the logs from Apex?",
    options: [
      { letter: "A", text: "System.out.println()" },
      { letter: "B", text: "System.debug()" },
      { letter: "C", text: "console.log()" },
      { letter: "D", text: "Logger.write()" },
    ],
    answer: "B",
    explanation: "System.debug() writes messages to the debug log, optionally with a logging level (e.g., LoggingLevel.ERROR).",
  },
  {
    id: "Q70",
    question: "Which tool lets developers deploy metadata between orgs using a package.xml manifest?",
    options: [
      { letter: "A", text: "Metadata API / Salesforce CLI" },
      { letter: "B", text: "Data Loader" },
      { letter: "C", text: "Process Builder" },
      { letter: "D", text: "Schema Builder" },
    ],
    answer: "A",
    explanation: "The Metadata API (used by Salesforce CLI, ANT, etc.) deploys metadata components defined in a package.xml manifest.",
  },
  {
    id: "Q71",
    question: "Which deployment tool is built into Setup and is intended for migrating metadata between related orgs (e.g., sandbox to production)?",
    options: [
      { letter: "A", text: "Change Sets" },
      { letter: "B", text: "Data Loader" },
      { letter: "C", text: "Workbench import" },
      { letter: "D", text: "Import Wizard" },
    ],
    answer: "A",
    explanation: "Change Sets are a point-and-click way to deploy metadata between orgs connected by a deployment connection.",
  },
  {
    id: "Q72",
    question: "When deploying to production via Change Set, what must pass for the deployment to succeed?",
    options: [
      { letter: "A", text: "All flows must be inactive" },
      { letter: "B", text: "Apex tests must pass and meet coverage requirements" },
      { letter: "C", text: "All validation rules must be deactivated" },
      { letter: "D", text: "All profiles must be included" },
    ],
    answer: "B",
    explanation: "Production deployments run Apex tests, which must pass and satisfy the 75% coverage requirement.",
  },
  {
    id: "Q73",
    question: "Which type of sandbox includes a copy of all production data?",
    options: [
      { letter: "A", text: "Developer sandbox" },
      { letter: "B", text: "Developer Pro sandbox" },
      { letter: "C", text: "Full sandbox" },
      { letter: "D", text: "Partial Copy sandbox" },
    ],
    answer: "C",
    explanation: "A Full sandbox replicates the entire production org, including all data; Partial Copy includes a sample, and Developer types include none.",
  },

  // ===== More Apex / Data =====
  {
    id: "Q74",
    question: "Which statement inserts a record if it is new or updates it if it already exists, based on ID or External ID?",
    options: [
      { letter: "A", text: "insert" },
      { letter: "B", text: "update" },
      { letter: "C", text: "upsert" },
      { letter: "D", text: "merge" },
    ],
    answer: "C",
    explanation: "upsert inserts or updates records based on the record ID or a specified External ID field.",
  },
  {
    id: "Q75",
    question: "Which exception type is thrown when a DML operation fails?",
    options: [
      { letter: "A", text: "DmlException" },
      { letter: "B", text: "QueryException" },
      { letter: "C", text: "NullPointerException" },
      { letter: "D", text: "ListException" },
    ],
    answer: "A",
    explanation: "DML failures throw a DmlException, which provides methods like getDmlMessage() and getDmlFieldNames().",
  },
  {
    id: "Q76",
    question: "What is the best way to avoid hitting SOQL governor limits inside a loop?",
    options: [
      { letter: "A", text: "Query inside the for loop for each record" },
      { letter: "B", text: "Move SOQL outside the loop and use collections/maps" },
      { letter: "C", text: "Use more @future calls" },
      { letter: "D", text: "Increase the API version" },
    ],
    answer: "B",
    explanation: "Bulkify by querying once outside the loop and using maps/sets, never placing SOQL or DML inside loops.",
  },
  {
    id: "Q77",
    question: "Which sObject method returns a map of field tokens for describing an object's schema?",
    options: [
      { letter: "A", text: "Schema.getGlobalDescribe()" },
      { letter: "B", text: "Schema.SObjectType.Account.getFieldsMap()" },
      { letter: "C", text: "getSObjectType().getDescribe().fields.getMap()" },
      { letter: "D", text: "All of these are valid describe approaches" },
    ],
    answer: "D",
    explanation: "Salesforce offers multiple describe APIs (getGlobalDescribe, schema tokens, fields.getMap) to inspect object/field metadata at runtime.",
  },
  {
    id: "Q78",
    question: "What does the 'final' keyword do when applied to an Apex variable?",
    options: [
      { letter: "A", text: "Makes it static" },
      { letter: "B", text: "Allows assignment only once (constant-like)" },
      { letter: "C", text: "Makes it global" },
      { letter: "D", text: "Makes it private" },
    ],
    answer: "B",
    explanation: "A final variable can be assigned only once, either at declaration or in a constructor/initializer.",
  },
  {
    id: "Q79",
    question: "Which access modifier makes an Apex method visible only within its defining class?",
    options: [
      { letter: "A", text: "global" },
      { letter: "B", text: "public" },
      { letter: "C", text: "protected" },
      { letter: "D", text: "private" },
    ],
    answer: "D",
    explanation: "private restricts visibility to the defining class; it is also the default if no modifier is specified.",
  },
  {
    id: "Q80",
    question: "Which access modifier is required to make an Apex class or method available to managed packages and other namespaces?",
    options: [
      { letter: "A", text: "public" },
      { letter: "B", text: "global" },
      { letter: "C", text: "protected" },
      { letter: "D", text: "private" },
    ],
    answer: "B",
    explanation: "global is required for code that must be accessible outside its namespace, such as in managed packages or webservice methods.",
  },
  {
    id: "Q81",
    question: "What is the difference between SOQL and SOSL?",
    options: [
      { letter: "A", text: "SOQL queries one object type; SOSL searches text across multiple objects" },
      { letter: "B", text: "SOQL searches text; SOSL queries one object" },
      { letter: "C", text: "They are identical" },
      { letter: "D", text: "SOSL can only be used in triggers" },
    ],
    answer: "A",
    explanation: "SOQL retrieves records from a single object (and related), while SOSL performs full-text searches across multiple objects.",
  },
  {
    id: "Q82",
    question: "Which keyword in Apex is used to define a custom exception class?",
    options: [
      { letter: "A", text: "extends Exception" },
      { letter: "B", text: "implements Exception" },
      { letter: "C", text: "throws Exception" },
      { letter: "D", text: "new Exception" },
    ],
    answer: "A",
    explanation: "A custom exception class must extend Exception, e.g., 'public class MyException extends Exception {}'.",
  },
  {
    id: "Q83",
    question: "Which loop variant is most efficient for iterating directly over query results without building an intermediate list?",
    options: [
      { letter: "A", text: "for (Account a : [SELECT Id FROM Account]) { }" },
      { letter: "B", text: "while (true) { }" },
      { letter: "C", text: "do { } while ()" },
      { letter: "D", text: "for (Integer i = 0; ...)" },
    ],
    answer: "A",
    explanation: "The SOQL for-loop iterates query results in batches of 200, which is memory-efficient for large result sets.",
  },
  {
    id: "Q84",
    question: "What does a Map<Id, Account> data structure provide?",
    options: [
      { letter: "A", text: "An ordered list of accounts" },
      { letter: "B", text: "Key-value pairs allowing fast lookup of an Account by its Id" },
      { letter: "C", text: "A set of unique account names" },
      { letter: "D", text: "A read-only collection" },
    ],
    answer: "B",
    explanation: "A Map stores key-value pairs; here it allows O(1) retrieval of an Account by its Id key.",
  },
  {
    id: "Q85",
    question: "Which constructor pattern quickly builds a Map keyed by record Id from a query?",
    options: [
      { letter: "A", text: "new Map<Id, Account>([SELECT Id, Name FROM Account])" },
      { letter: "B", text: "new Map<Id, Account>(accountList.keySet())" },
      { letter: "C", text: "Map.putAll(SELECT...)" },
      { letter: "D", text: "new List<Map>()" },
    ],
    answer: "A",
    explanation: "Passing a query/list of sObjects to a Map<Id, sObject> constructor auto-keys the map by record Id.",
  },

  // ===== Security & Misc =====
  {
    id: "Q86",
    question: "Which method enforces field-level security in Apex by stripping inaccessible fields from query results?",
    options: [
      { letter: "A", text: "Security.stripInaccessible()" },
      { letter: "B", text: "Schema.isAccessible()" },
      { letter: "C", text: "System.runAs()" },
      { letter: "D", text: "WITH SECURITY_ENFORCED only" },
    ],
    answer: "A",
    explanation: "Security.stripInaccessible() removes fields/records the user can't access from sObjects, helping enforce FLS and object permissions.",
  },
  {
    id: "Q87",
    question: "Which SOQL clause throws an exception if the running user lacks access to a referenced field or object?",
    options: [
      { letter: "A", text: "WITH SECURITY_ENFORCED" },
      { letter: "B", text: "ALL ROWS" },
      { letter: "C", text: "FOR UPDATE" },
      { letter: "D", text: "GROUP BY" },
    ],
    answer: "A",
    explanation: "WITH SECURITY_ENFORCED applies field- and object-level security checks to the query and throws if access is missing.",
  },
  {
    id: "Q88",
    question: "What is the recommended way to grant a user access to a specific Apex class or object permission additively?",
    options: [
      { letter: "A", text: "Modify their profile directly for each user" },
      { letter: "B", text: "Assign a Permission Set" },
      { letter: "C", text: "Use a sharing rule" },
      { letter: "D", text: "Change the org-wide default" },
    ],
    answer: "B",
    explanation: "Permission Sets grant additional permissions on top of a profile without changing the profile itself.",
  },
  {
    id: "Q89",
    question: "Which Apex method checks whether the current user can create records of a given object?",
    options: [
      { letter: "A", text: "Schema.sObjectType.Account.isCreateable()" },
      { letter: "B", text: "Account.canCreate()" },
      { letter: "C", text: "System.canInsert()" },
      { letter: "D", text: "Account.isInsertable()" },
    ],
    answer: "A",
    explanation: "DescribeSObjectResult methods like isCreateable(), isAccessible(), isUpdateable(), and isDeletable() check CRUD permissions.",
  },
  {
    id: "Q90",
    question: "What is a custom setting primarily used for?",
    options: [
      { letter: "A", text: "Storing large transactional data" },
      { letter: "B", text: "Storing reusable application configuration data accessible without SOQL (cached)" },
      { letter: "C", text: "Replacing triggers" },
      { letter: "D", text: "Scheduling jobs" },
    ],
    answer: "B",
    explanation: "Custom Settings store app configuration (list or hierarchy) in the application cache, accessible without SOQL queries.",
  },
  {
    id: "Q91",
    question: "What is a key advantage of Custom Metadata Types over Custom Settings?",
    options: [
      { letter: "A", text: "They store user-specific data" },
      { letter: "B", text: "Their records are metadata and can be deployed/packaged between orgs" },
      { letter: "C", text: "They cannot be queried" },
      { letter: "D", text: "They count against data storage heavily" },
    ],
    answer: "B",
    explanation: "Custom Metadata Type records are deployable metadata, so configuration can be migrated via change sets/packages, unlike custom setting data.",
  },
  {
    id: "Q92",
    question: "Which formula function returns the number of days between two dates?",
    options: [
      { letter: "A", text: "DATEVALUE()" },
      { letter: "B", text: "Subtracting one Date from another (date1 - date2)" },
      { letter: "C", text: "DAYS()" },
      { letter: "D", text: "NOW()" },
    ],
    answer: "B",
    explanation: "In formulas, subtracting one Date from another returns the integer number of days between them.",
  },
  {
    id: "Q93",
    question: "Which feature should be used to call an Apex class from a Flow?",
    options: [
      { letter: "A", text: "A method annotated with @InvocableMethod" },
      { letter: "B", text: "A @future method" },
      { letter: "C", text: "A @RemoteAction method" },
      { letter: "D", text: "A trigger" },
    ],
    answer: "A",
    explanation: "Flows can call Apex via an @InvocableMethod (Apex Action element).",
  },
  {
    id: "Q94",
    question: "A platform event is best described as what?",
    options: [
      { letter: "A", text: "A synchronous database trigger" },
      { letter: "B", text: "A message used for event-driven, publish-subscribe communication" },
      { letter: "C", text: "A scheduled job" },
      { letter: "D", text: "A type of validation rule" },
    ],
    answer: "B",
    explanation: "Platform Events enable an event-driven architecture using a publish-subscribe model for decoupled communication.",
  },
  {
    id: "Q95",
    question: "Which keyword publishes a platform event in Apex?",
    options: [
      { letter: "A", text: "insert (EventBus is implicit) / EventBus.publish()" },
      { letter: "B", text: "System.publish()" },
      { letter: "C", text: "Event.fire()" },
      { letter: "D", text: "Database.emit()" },
    ],
    answer: "A",
    explanation: "Publish platform events using EventBus.publish(eventList) (or insert on the event sObject in older patterns).",
  },
  {
    id: "Q96",
    question: "Which order is correct in the Salesforce order of execution for a record save?",
    options: [
      { letter: "A", text: "Before triggers run before validation rules, after triggers run after validation rules" },
      { letter: "B", text: "Validation rules run, then before triggers, then after triggers" },
      { letter: "C", text: "Before triggers, then validation rules, then after triggers" },
      { letter: "D", text: "After triggers run before before triggers" },
    ],
    answer: "C",
    explanation: "Simplified order: system validation, before triggers, custom validation rules, save (not committed), after triggers, assignment/workflow, commit.",
  },
  {
    id: "Q97",
    question: "When do duplicate rules and validation rules run relative to before-save flows?",
    options: [
      { letter: "A", text: "Before-save flows run before validation rules" },
      { letter: "B", text: "Validation rules always run first" },
      { letter: "C", text: "Before-save flows never run with validation rules" },
      { letter: "D", text: "After triggers run first" },
    ],
    answer: "A",
    explanation: "In the order of execution, before-save record-triggered flows execute before standard validation rules.",
  },
  {
    id: "Q98",
    question: "What is the heap size limit for synchronous Apex transactions?",
    options: [
      { letter: "A", text: "3 MB" },
      { letter: "B", text: "6 MB" },
      { letter: "C", text: "12 MB" },
      { letter: "D", text: "1 MB" },
    ],
    answer: "B",
    explanation: "Synchronous Apex has a 6 MB heap limit; asynchronous Apex (batch, future, queueable) gets 12 MB.",
  },
  {
    id: "Q99",
    question: "What is the maximum CPU time for a synchronous Apex transaction?",
    options: [
      { letter: "A", text: "10,000 ms" },
      { letter: "B", text: "60,000 ms" },
      { letter: "C", text: "5,000 ms" },
      { letter: "D", text: "Unlimited" },
    ],
    answer: "A",
    explanation: "Synchronous transactions allow 10,000 ms of CPU time; asynchronous transactions allow 60,000 ms.",
  },
  {
    id: "Q100",
    question: "Which two are valid ways to expose Apex logic to an external system as a REST endpoint? (Choose 2)",
    options: [
      { letter: "A", text: "Annotate a class with @RestResource and methods with @HttpGet/@HttpPost" },
      { letter: "B", text: "Create a SOAP web service method with the 'webservice' keyword" },
      { letter: "C", text: "Use a @future method" },
      { letter: "D", text: "Use a validation rule" },
    ],
    answer: "A, B",
    explanation: "@RestResource exposes a custom REST API; the 'webservice' keyword exposes a SOAP API. Both let external systems call Apex.",
  },
];
